#!/usr/bin/env python3
"""Download the webfonts locally and emit @font-face rules, so the site stops
calling Google on every page load.

WHY
    styles.css line 1 was an @import of fonts.googleapis.com. That is the slowest
    possible way to load a font: the browser has to fetch styles.css, parse it, THEN
    discover and fetch Google's CSS, THEN discover and fetch the woff2 files. Three
    serial hops across two extra origins. Self-hosting collapses it to one.

    It is also the difference between Google seeing the IP of every visitor to an
    immigration site and Google seeing nothing. German courts have held that embedding
    Google Fonts without consent breaches GDPR, and this site has EU-reachable readers.

    And it makes the Content-Security-Policy simpler rather than longer: font-src stays
    'self' and style-src needs no new entry, instead of allowlisting two Google hosts
    whose file paths are versioned (/s/inter/v20/...) and can move under us.

WHAT IT DOES
    Asks Google for the same CSS a modern Chrome would get (so we get woff2, not ttf),
    keeps only the latin and latin-ext subsets, downloads those woff2 files into fonts/,
    and writes fonts/fonts.css with the src rewritten to local paths. Google's own
    subsetting and unicode-range values are preserved verbatim, so the browser still
    downloads only the ranges a page actually uses and rendering is unchanged.

    Deliberately drops cyrillic, greek, hebrew, vietnamese, math and symbols: this is an
    English-language site, and unicode-range means an unused subset would never be
    downloaded anyway, so shipping them is dead weight in the repo.

USAGE
    python3 automation/fetch_fonts.py            # dry run: report what it would fetch
    python3 automation/fetch_fonts.py --commit   # download + write fonts/fonts.css

    Re-run after changing which weights the CSS uses. FAMILIES below is the source of
    truth and must match the font-weight values actually present in styles.css.
"""

import argparse
import io
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
FONT_DIR = os.path.join(REPO, "fonts")

# Must match the weights styles.css actually uses. Verified 2026-09-02:
# Open Sans 300 (1 use), 400 (10), 600 (83), 700 (111); Inter is --font-display at
# 500/600/700, plus 800 for the og.html headline and 4 uses in styles.css.
# Keep this list in sync or a weight will silently synthesise. Widening the range
# on a VARIABLE font costs zero extra bytes - it is the same file either way.
FAMILIES = "family=Inter:wght@500;600;700&family=Open+Sans:wght@300;400;600;700;800"
CSS_URL = "https://fonts.googleapis.com/css2?%s&display=swap" % FAMILIES

# A real Chrome UA, because the response format is UA-dependent: older UAs get ttf.
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

KEEP_SUBSETS = {"latin", "latin-ext"}

BLOCK_RE = re.compile(
    r"/\*\s*(?P<subset>[a-z-]+)\s*\*/\s*@font-face\s*\{(?P<body>[^}]*)\}", re.I)


def get(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=45) as r:
        data = r.read()
    return data if binary else data.decode("utf-8")


def field(body, name):
    m = re.search(name + r"\s*:\s*([^;]+);", body, re.I)
    return m.group(1).strip() if m else None


def slug(family, subset):
    """Name by family+subset only, NOT by weight.

    Both families are served as VARIABLE fonts: Google returns one woff2 per
    (family, subset) and repeats that same URL in every per-weight @font-face block.
    The browser dedupes on URL, so it downloads the file once. Naming the local copies
    per weight would defeat that and make the browser fetch three byte-identical Inter
    files and four identical Open Sans ones - verified by md5: 14 blocks collapse to
    exactly 4 distinct files (207 KB, not 679 KB).
    """
    return "%s-%s.woff2" % (family.lower().replace(" ", "-").strip("'\""), subset)



BEGIN = "/* FONTS:BEGIN generated by automation/fetch_fonts.py - do not hand-edit */"
END = "/* FONTS:END */"


def inline_into(path, css, only_family=None):
    """Replace the marker-delimited region in path with the generated @font-face rules.

    Inlined rather than @import'ed on purpose: an @import would reintroduce the extra
    request that self-hosting exists to remove.
    """
    s = io.open(path, encoding="utf-8").read()
    if BEGIN not in s or END not in s:
        print("  %s: markers missing, skipped" % path, file=sys.stderr)
        return False
    blocks = [b for b in css.strip().split("\n\n") if b.strip()]
    if only_family:
        key = only_family.lower().replace(" ", "-")
        blocks = [b for b in blocks if key in b]
    head, rest = s.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    io.open(path, "w", encoding="utf-8").write(
        head + BEGIN + "\n" + "\n".join(blocks) + "\n" + END + tail)
    print("  %s: %d @font-face block(s) inlined" % (path, len(blocks)))
    return True


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--commit", action="store_true", help="download and write (default: dry run)")
    args = ap.parse_args()

    css = get(CSS_URL)
    blocks = list(BLOCK_RE.finditer(css))
    if not blocks:
        print("could not parse any @font-face blocks from Google's CSS", file=sys.stderr)
        return 1

    kept, total_bytes, out = [], 0, []
    for m in blocks:
        subset = m.group("subset").lower()
        if subset not in KEEP_SUBSETS:
            continue
        body = m.group("body")
        family = (field(body, "font-family") or "").strip("'\"")
        weight = field(body, "font-weight") or "400"
        style = field(body, "font-style") or "normal"
        urange = field(body, "unicode-range") or ""
        src = field(body, "src") or ""
        um = re.search(r"url\((https://[^)]+\.woff2)\)", src)
        if not (family and um):
            continue
        name = slug(family, subset)
        kept.append((name, um.group(1), family, weight, style, urange, subset))

    # Collapse the per-weight blocks into one per (family, subset), carrying the min and
    # max requested weight so the variable font covers the whole range in one download.
    faces = {}
    for name, url, family, weight, style, urange, subset in kept:
        try:
            wnum = int(weight)
        except ValueError:
            wnum = 400
        f = faces.get(name)
        if f is None:
            faces[name] = {"url": url, "family": family, "style": style,
                           "urange": urange, "subset": subset,
                           "wmin": wnum, "wmax": wnum, "urls": {url}}
        else:
            f["wmin"] = min(f["wmin"], wnum)
            f["wmax"] = max(f["wmax"], wnum)
            f["urls"].add(url)

    # If Google ever stops serving a single variable file per subset, the collapse above
    # would silently drop weights. Fail loudly instead of shipping wrong fonts.
    multi = {n: sorted(f["urls"]) for n, f in faces.items() if len(f["urls"]) > 1}
    if multi:
        print("ABORTING: these are not single variable files any more, so one file per\n"
              "(family, subset) would lose weights. Revert to per-weight filenames:",
              file=sys.stderr)
        for n, us in multi.items():
            print("  %s -> %d distinct URLs" % (n, len(us)), file=sys.stderr)
        return 1

    if not kept:
        print("nothing matched the kept subsets (%s)" % ", ".join(sorted(KEEP_SUBSETS)),
              file=sys.stderr)
        return 1

    print("%d per-weight block(s) collapsed to %d file(s) across subsets %s\n"
          % (len(kept), len(faces), ", ".join(sorted(KEEP_SUBSETS))))
    if args.commit:
        os.makedirs(FONT_DIR, exist_ok=True)

    for name in sorted(faces):
        f = faces[name]
        if args.commit:
            blob = get(f["url"], binary=True)
            with open(os.path.join(FONT_DIR, name), "wb") as fh:
                fh.write(blob)
            n = len(blob)
        else:
            n = 0
        total_bytes += n
        wrange = ("%d" % f["wmin"]) if f["wmin"] == f["wmax"] else ("%d %d" % (f["wmin"], f["wmax"]))
        print("  %-30s %-12s wght %-8s %s"
              % (name, f["family"], wrange, "%6d b" % n if n else ""))
        out.append(
            "@font-face {\n"
            "  font-family: '%s';\n"
            "  font-style: %s;\n"
            "  font-weight: %s;\n"
            "  font-display: swap;\n"
            "  src: url('fonts/%s') format('woff2');\n"
            "  unicode-range: %s;\n"
            "}\n" % (f["family"], f["style"], wrange, name, f["urange"]))

    if not args.commit:
        print("\nDry run: nothing written. Re-run with --commit.")
        return 0

    header = (
        "/* Self-hosted webfonts. GENERATED by automation/fetch_fonts.py - do not hand-edit.\n"
        " * Regenerate after changing which weights styles.css uses.\n"
        " *\n"
        " * These are Google's own woff2 files with Google's own subsetting and\n"
        " * unicode-range values preserved, so the browser still fetches only the ranges a\n"
        " * page needs and rendering is byte-for-byte what fonts.googleapis.com served.\n"
        " * Serving them ourselves removes two network hops and two third-party origins,\n"
        " * and keeps font-src 'self' in the CSP.\n"
        " *\n"
        " * Paths are relative, so they resolve against styles.css wherever the site is\n"
        " * hosted - no absolute host to update at a domain cutover.\n"
        " */\n\n")
    with open(os.path.join(FONT_DIR, "fonts.css"), "w", encoding="utf-8") as fh:
        fh.write(header + "\n".join(out))

    print("\nwrote fonts/fonts.css  (%d faces, %.1f KB of woff2 total)"
          % (len(kept), total_bytes / 1024.0))
    faces_css = "\n".join(out)
    inline_into(os.path.join(REPO, "styles.css"), faces_css)
    inline_into(os.path.join(REPO, "og.html"), faces_css, only_family="Open Sans")
    print("Next: re-run the CSP violation sweep; nothing should reference Google any more.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
